site_name: Kieran's notes

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    scheme: slate
    primary: black
    accent: blue

nav:
  - Home: index.md
  - Python data science topics:
        - Reading data: python-data-science/reading-data.md
        - SQLite and pandas: python-data-science/sqlite-pandas.md
        - Basic Python data operations: python-data-science/data-operations.md
        - Working with strings in Python: python-data-science/python-strings.md
        - Working with plots: python-data-science/plots.md
        - Regression: python-data-science/regression.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js