site_name: Kieran's notes

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Linux essentials:
      - Linux command line:
          - Commands and permissions: linux-essentials/linux-command-line/commands-and-permissions.md
          - Help commands and pipes: linux-essentials/linux-command-line/help-commands-and-pipes.md
          - File commands and filters: linux-essentials/linux-command-line/file-commands.md
          - Text and grep commands: linux-essentials/linux-command-line/text-and-grep-commands.md
          - File comparison and splitting: linux-essentials/linux-command-line/file-comparison-and-splitting.md
      - Linux administration:
          - Utility commands and user management: linux-essentials/linux-administration/utility-commands-user-management.md
  - Bioinformatics algorithms:
      - Where in the genome does DNA replication begin?: bioinformatics-algorithms/where-in-genome-does-dna-replication-begin.md
  - AWS Cloud Practitioner Essentials:
      - Introduction to Amazon Web Services (AWS): aws-cloud-practitioner-essentials/intro-to-aws.md
      - Compute in the cloud: aws-cloud-practitioner-essentials/compute-in-the-cloud.md
      - Global infrastructure and reliability: aws-cloud-practitioner-essentials/global-infrastructure-and-reliability.md
      - Networking: aws-cloud-practitioner-essentials/networking.md
      - Storage and databases: aws-cloud-practitioner-essentials/storage-and-databases.md
      - Security: aws-cloud-practitioner-essentials/security.md
      - Pricing and support: aws-cloud-practitioner-essentials/pricing-and-support.md
      - Migration and innovation: aws-cloud-practitioner-essentials/migration-and-innovation.md
      - Well-architected framework: aws-cloud-practitioner-essentials/well-architected-framework.md
  - AWS Certified Solutions Architect:
      - Launching EC2 instances: solutions-architect/launching-ec2-instances.md
      - Introduction to Amazon Simple Storage Service: solutions-architect/amazon-s3.md
      - Introduction to Amazon DynamoDB: solutions-architect/dynamodb.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js