site_name: Kieran's notes

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Linux essentials:
      - Linux command line:
          - Commands and permissions: linux-essentials/linux-command-line/commands-and-permissions.md
          - Help commands and pipes: linux-essentials/linux-command-line/help-commands-and-pipes.md
          - File commands and filters: linux-essentials/linux-command-line/file-commands.md
          - Text and grep commands: linux-essentials/linux-command-line/text-and-grep-commands.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js