site_name: Kieran's notes

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    scheme: slate
    primary: black
    accent: blue

nav:
  - Home: index.md
  - Python data science topics:
        - Importing and cleaning data: python-data-science/importing-cleaning-data.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js